id = "objectscript"
name = "InterSystems ObjectScript Routine"
version = "1.0.0"
schema_version = 1
authors = ["Dave McCaldon <davem@intersystems.com>","Hannah Kimura <hannah.kimura@intersystems.com>"]
description = "InterSystems IRIS ObjectScript Routine Extension"
repository = "https://github.com/hkimura-intersys/zed-objectscript-extension"

[grammars.objectscript_routine]
repository = "https://github.com/intersystems/tree-sitter-objectscript"
commit = "e492601cb5b4564fdf41e5a1800432a3ee4cf74f"
path = "objectscript_routine"

